### ISSUE TITLE
Installation error (with mitigation)

### ISSUE THREAD

**Issue by ftdot** [Secret-chest/fancify-text#2]
### Issue

When I tried to install this library, I got the error:

```
$ pip install fancify-text
Collecting fancify-text
  Downloading fancify-text-0.2.3.tar.gz (14 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "...\AppData\Local\Temp\pip-install-d0k0_gwn\fancify-text_aa471b6c6f9948aca78bb58de9ab44b1\setup.py", line 14, in <module>
          long_description=open("README.md").read(),
                           ^^^^^^^^^^^^^^^^^^^^^^^^
        File "...\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1251.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 424: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

OS: `Windows`
Python version: `3.11`

> **Note**
>
> `setup.py` "scripts" idea is cool and lightweight, but this is doesn't work on Windows.
> You can use "entry-points" instead of "scripts". If you continue development of this
> library, you may take look at [this issue](https://stackoverflow.com/questions/18787036/difference-between-entry-points-console-scripts-and-scripts-in-setup-py)
>
> But, thanks, this library was useful!

### Mitigtation

File `setup.py`, line `14`. Default encoding is `charmap`, change it to `utf8` with adding `encoding=`:

```py
    ...
    long_description=open("README.md", encoding="utf8").read(),
    ...
```

**Comment by Secret-chest** [comment]
Can you send a PR? I can only use linux.

**Comment by ftdot** [comment]
Sure, I can
